-- CREATE TABLE customers (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   first_name TEXT NOT NULL,
--   last_name TEXT NOT NULL,
--   phone_number TEXT NOT NULL UNIQUE
-- );

-- CREATE TABLE addresses (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     customer_id INTEGER,
--     adress_details TEXT NOT NULL,
--     state TEXT NOT NULL,
--     pin_code TEXT NOT NULL,
--     FOREIGN KEY (customer_id) REFERENCES customers(id)
-- );